In [100]:
import numpy as np

In [101]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

creating array

In [102]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [103]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [104]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [105]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [106]:
a[2] = 10
a 

array([ 1,  2, 10,  4,  5])

In [107]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [108]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multi Dementional Arrays 

In [109]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [110]:
n = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [111]:
n[0,2] = 20
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [112]:
n[0]

array([ 1,  2, 20])

In [113]:
n[:,1]

array([2, 5, 8])

In [114]:
n[:,2] = [1,2,3]
n

array([[1, 2, 1],
       [4, 5, 2],
       [7, 8, 3]])

Randomly generated arrays

In [115]:
np.random.seed(2)  # seed for the random number generator
l = np.random.rand(5,2)
l

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [116]:
l*100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [117]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [118]:
np.random.seed(2)
np.random.randint(low=1, high=100, size=(5,2))

array([[41, 16],
       [73, 23],
       [44, 83],
       [76,  8],
       [35, 50]])

Element-wise operations

In [119]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [120]:
b = ((a*2) + 10)**2/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [121]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

Comparison operations

In [122]:
a

array([0, 1, 2, 3, 4])

In [123]:
a >= 2

array([False, False,  True,  True,  True])

In [125]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [127]:
a > b

array([False, False,  True,  True,  True])

In [130]:
a[a > b] # returns the elements of a that are greater than b or whatever the condition inside is true

array([2, 3, 4])

Summarizing operations

In [132]:
a

array([0, 1, 2, 3, 4])

In [136]:
a.std()


np.float64(1.4142135623730951)