In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 4, 5, 6,10])
a

array([ 1,  2,  3,  4,  5,  6, 10])

In [8]:
a[2]

np.int64(3)

In [9]:
a[2] = 45
a[2]

np.int64(45)

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

# Multi dimensional arrays

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
n[1]

array([4, 5, 6])

In [20]:
n[1,2]

np.int64(6)

In [21]:
n[2] = [4,6,8]
n

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 8]])

In [24]:
n[2,2] =89
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 4,  6, 89]])

In [25]:
n[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 4,  6, 89]])

In [29]:
n[:3,:2]

array([[1, 2],
       [4, 5],
       [4, 6]])

# Randomly Generated arrays

In [31]:
np.random.rand(5,2)

array([[0.07155192, 0.8461081 ],
       [0.62929195, 0.46011004],
       [0.07934614, 0.9973355 ],
       [0.63016228, 0.32949161],
       [0.91493076, 0.71942232]])

In [34]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [35]:
np.random.randint(low=0, high=100, size=(5,2))

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

# Element-wise operations

In [37]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [38]:
a * 2

array([0, 2, 4, 6, 8])

In [40]:
b = (10 + (a*2)) ** 2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [41]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [43]:
(a * 2) + b

array([ 1.  ,  3.44,  5.96,  8.56, 11.24])

# Comparison operations

In [44]:
a

array([0, 1, 2, 3, 4])

In [45]:
a >= 2

array([False, False,  True,  True,  True])

In [46]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [51]:
b > a

array([ True,  True, False, False, False])

In [52]:
b[b > a]

array([1.  , 1.44])

# Summarizing operations

In [53]:
a

array([0, 1, 2, 3, 4])

In [54]:
a.max()

np.int64(4)

In [55]:
a.sum()

np.int64(10)

In [56]:
n.sum()

np.int64(120)

In [57]:
a.std()

np.float64(1.4142135623730951)