In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 4, 5, 6,10])
a

array([ 1,  2,  3,  4,  5,  6, 10])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2] = 45
a[2]

np.int64(45)

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

# Multi dimensional arrays

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
n[1]

array([4, 5, 6])

In [14]:
n[1,2]

np.int64(6)

In [15]:
n[2] = [4,6,8]
n

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 8]])

In [16]:
n[2,2] =89
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 4,  6, 89]])

In [17]:
n[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 4,  6, 89]])

In [18]:
n[:3,:2]

array([[1, 2],
       [4, 5],
       [4, 6]])

# Randomly Generated arrays

In [19]:
np.random.rand(5,2)

array([[0.01929825, 0.61173455],
       [0.83838583, 0.94268422],
       [0.70869769, 0.78884145],
       [0.46413943, 0.13251451],
       [0.2336176 , 0.74115577]])

In [20]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [21]:
np.random.randint(low=0, high=100, size=(5,2))

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

# Element-wise operations

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a * 2

array([0, 2, 4, 6, 8])

In [24]:
b = (10 + (a*2)) ** 2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [25]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [26]:
(a * 2) + b

array([ 1.  ,  3.44,  5.96,  8.56, 11.24])

# Comparison operations

In [27]:
a

array([0, 1, 2, 3, 4])

In [28]:
a >= 2

array([False, False,  True,  True,  True])

In [29]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [30]:
b > a

array([ True,  True, False, False, False])

In [31]:
b[b > a]

array([1.  , 1.44])

# Summarizing operations

In [32]:
a

array([0, 1, 2, 3, 4])

In [33]:
a.max()

np.int64(4)

In [34]:
a.sum()

np.int64(10)

In [35]:
n.sum()

np.int64(120)

In [36]:
a.std()

np.float64(1.4142135623730951)

# Multiplication

In [69]:
np.random.seed(4)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.random.randint(low=0, high=10, size=(3,3))
d = np.random.randint(low=0, high=20, size=(3,3))
print(f"shape: {a.shape}")
print(f"shape: {b.shape}")
print(f"shape: {c.shape}, {c}")
print(f"shape: {d.shape}, {d}")

shape: (3,)
shape: (3,)
shape: (3, 3), [[7 5 1]
 [8 7 8]
 [2 9 7]]
shape: (3, 3), [[13  8  4]
 [18 12  6]
 [10  3  0]]


In [ ]:
def vector_vector_multiplication(U, V):
    assert U.shape[0] == V.shape[0], "vector1.shape != vector2.shape"
    n = U.shape[0]
    result = 0.0
    for i in range(n):
        result = result + U[i] * V[i]
        
    return result

In [63]:
vector_vector_multiplication(a, b)

np.float64(32.0)

In [70]:
def matrix_vector_multiplication(U, V):
    assert U.shape[1] == V.shape[0], "matrix cols != vector rows"
    
    result = np.zeros(U.shape[0])
    
    for i in range(U.shape[1]):
        result[i] = vector_vector_multiplication(U[i], V)
        
    return result

In [ ]:
matrix_vector_multiplication(c, a)

array([20, 46, 41])

In [78]:
np.dot(c,a)

array([20, 46, 41])

In [79]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0], "matrix1 cols != matrix2 rows"
    
    result = np.zeros((U.shape[0], V.shape[1]))
    
    for i in range(V.shape[1]):
        result[:, i] = matrix_vector_multiplication(U, V[:, i])
    
    return result

In [80]:
matrix_matrix_multiplication(c,d)

array([[191., 119.,  58.],
       [310., 172.,  74.],
       [258., 145.,  62.]])

In [77]:
np.dot(c,d)

array([[191, 119,  58],
       [310, 172,  74],
       [258, 145,  62]])