In [67]:
import numpy as np

In [68]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

Multiplication

In [69]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [70]:
u.shape[0]  #returns the number of elements in the array

4

In [71]:
def vector_vector_multiplication(u,v):
    result = 0
    assert u.shape[0] == v.shape[0]
    n = u.shape[0] #4
    
    for i in range(n):
        result += u[i] * v[i]
    
    return result
     

In [72]:
print(vector_vector_multiplication(u,v))

14


In [73]:
u.dot(v) #numpy function to multiply two vectors

np.int64(14)

In [74]:
U = np.array([[2,4,5,6],
              [1,2,1,2],
              [3,1,2,1]])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [75]:
U.shape[0]

3

In [76]:
def matrix_vector_multiplication(U,v):
    number_of_rows = U.shape[0]
    number_of_columns = U.shape[1]
    assert number_of_columns == v.shape[0]
    
    result = np.zeros(number_of_rows)
    
    for i in range(number_of_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    
    return result

In [77]:
print(matrix_vector_multiplication(U,v))

[14.  5.  5.]


In [78]:
U.dot(v) #numpy function to multiply a matrix and a vector

array([14,  5,  5])

In [96]:
V = np.array([[1,1,2],
              [0,0.5,1],
              [0,2,1],
              [2,1,0]
            ])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [80]:
def matrix_matrix_multiplication(U,V):
    number_of_rows_u = U.shape[0]
    number_of_columns_u = U.shape[1]
    number_of_rows_v = V.shape[0]
    number_of_columns_v = V.shape[1]
    
    assert number_of_columns_u == number_of_rows_v
    
    result = np.zeros((number_of_rows_u,number_of_columns_v))
    
    for i in range(number_of_columns_v):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i] = Uvi
        
    return result
        

In [82]:
print(matrix_matrix_multiplication(U,V))

[[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]


In [84]:
U.dot(V) #numpy function to multiply two matrices

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

Identity Matrix

In [100]:
I = np.eye(3) #identity matrix
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [104]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

Inverse

In [105]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [107]:
np.linalg.inv(Vs)

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [108]:
Vs.dot(np.linalg.inv(Vs))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])